apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  type: NodePort
  selector:
    app: student-app
  ports:
    - port: 8089        # port du Service (interne Kubernetes)
      targetPort: 8089  # port du container (Tomcat)
      nodePort: 30080   # port accessible depuis ton PC

